name: API Automation Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run tests against
        required: true
        default: qa
        type: choice
        options:
          - qa
          - staging

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Give Gradle wrapper permission
        run: chmod +x gradlew

      - name: Run API tests
        env:
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
        run: ./gradlew clean test -Denv=${{ inputs.environment }}

      - name: Generate Allure report
        if: always()
        run: ./gradlew allureReport

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report

